#Librerias
library(shiny)
library(bs4Dash)
library(vroom)
library(tidyr)
library(tidyverse)
library(dplyr)
library(leaflet)
library(plotly)
library(rgdal)
library(raster)
library(geojsonsf)
library(sf)
#remotes::install_github("Displayr/flipTime")
library(flipTime)
library(units)

